version: '3.7'

networks:
  web:
    external: true

services:
  application:
    container_name: inventar_application
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev
    command: runsvdir /etc/service
    extra_hosts:
      - 'inventar.localhost:127.0.0.1'
      - 'inventar.localhost.chaostreff-flensburg.de:127.0.0.1'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inventar.rule=Host(`inventar.localhost`,`inventar.localhost.chaostreff-flensburg.de`)"
      - "traefik.http.routers.inventar.entrypoints=web"
      - "traefik.http.services.inventar.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - 'USER_ID=${USER_ID:-0}'
      - 'GROUP_ID=${GROUP_ID:-0}'
      - STARTUP_COMMAND1=/home/app/modules/createLogs.sh
      - STARTUP_COMMAND2=touch /opt/app/storage/app/laravel.sqlite
      - STARTUP_COMMAND3=composer install --no-progress --no-interaction
      - STARTUP_COMMAND4=npm install
      - STARTUP_COMMAND5=npm run dev
      - STARTUP_COMMAND6=/home/app/modules/recreateUserWithOwnIds.sh
      - STARTUP_COMMAND7=/home/app/modules/ownerships.sh
      - STARTUP_COMMAND8=php artisan migrate --force &
    volumes:
      - '.:/opt/app:cached'
      - './docker/app/.bashrc:/home/www-data/.bashrc:cached'
    restart: unless-stopped

